server:
  port: 8009
#servlet:
# context-path: /server-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/  # 服务中心地址
spring:
  application:
    name: server-zuul
zuul:
 routes: 
    config-client:
      path: /config-client/**
      serviceId: config-client
      strip-prefix: false 
    server-client:
      path: /server-client/**
      serviceId: server-client
      strip-prefix: false 
      
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1      